"""Partial stub for optional ``pynvml`` (``nvidia-ml-py``); runtime imports stay lazy."""

from typing import Any

def nvmlInit() -> None: ...
def nvmlDeviceGetCount() -> int: ...
def nvmlDeviceGetHandleByIndex(index: int) -> Any: ...

class UtilizationRates:
    gpu: int

def nvmlDeviceGetUtilizationRates(handle: Any) -> UtilizationRates: ...
