"""Training service constants and defaults with explicit operational intent."""

from __future__ import annotations

import os
from enum import StrEnum


class TrainingConfigKey(StrEnum):
    """Environment keys used to configure training orchestration/runtime."""

    RAY_ADDRESS = "TRAINING_RAY_ADDRESS"
    RETRAINING_LABEL_THRESHOLD = "RETRAINING_LABEL_THRESHOLD"
    RETRAINING_REWARD_BLEND_ALPHA = "RETRAINING_REWARD_BLEND_ALPHA"
    REGRESSION_CHECK_INTERVAL_SECONDS = "REGRESSION_CHECK_INTERVAL_SECONDS"


# rank=16 is the standard LoRA default; higher rank captures more task-specific
# information at the cost of more trainable parameters and memory.
DEFAULT_LORA_RANK = 16
DEFAULT_LORA_ALPHA = 32.0
DEFAULT_LORA_DROPOUT = 0.1
DEFAULT_TARGET_MODULES = ["q_proj", "v_proj"]
DEFAULT_LEARNING_RATE = 2e-4
DEFAULT_NUM_EPOCHS = 3
DEFAULT_BATCH_SIZE = 4
DEFAULT_GRADIENT_ACCUMULATION_STEPS = 4
DEFAULT_MAX_SEQ_LEN = 2048
DEFAULT_WARMUP_STEPS = 100
DEFAULT_SAVE_STEPS = 500
DEFAULT_EVAL_STEPS = 500
DEFAULT_USE_QLORA = False
DEFAULT_RETRAINING_LABEL_THRESHOLD = int(
    os.environ.get(TrainingConfigKey.RETRAINING_LABEL_THRESHOLD, "1000")
)
DEFAULT_RETRAINING_REWARD_BLEND_ALPHA = float(
    os.environ.get(TrainingConfigKey.RETRAINING_REWARD_BLEND_ALPHA, "0.7")
)
DEFAULT_REGRESSION_CHECK_INTERVAL_SECONDS = int(
    os.environ.get(TrainingConfigKey.REGRESSION_CHECK_INTERVAL_SECONDS, "3600")
)
GRADIENT_NORM_WARNING_THRESHOLD = 10.0


__all__ = [
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_EVAL_STEPS",
    "DEFAULT_GRADIENT_ACCUMULATION_STEPS",
    "DEFAULT_LEARNING_RATE",
    "DEFAULT_LORA_ALPHA",
    "DEFAULT_LORA_DROPOUT",
    "DEFAULT_LORA_RANK",
    "DEFAULT_MAX_SEQ_LEN",
    "DEFAULT_NUM_EPOCHS",
    "DEFAULT_REGRESSION_CHECK_INTERVAL_SECONDS",
    "DEFAULT_RETRAINING_LABEL_THRESHOLD",
    "DEFAULT_RETRAINING_REWARD_BLEND_ALPHA",
    "DEFAULT_SAVE_STEPS",
    "DEFAULT_TARGET_MODULES",
    "DEFAULT_USE_QLORA",
    "DEFAULT_WARMUP_STEPS",
    "GRADIENT_NORM_WARNING_THRESHOLD",
    "TrainingConfigKey",
]
